### ISSUE TITLE
Original author of iOS

### ISSUE THREAD

**Issue by gebes** [didiabel/native_dialog_plus#12]
Why did you copy my package instead of just opening a PR or contributing? Stuff like this just clutters the Flutter ecosystem

**Comment by didiabel** [comment]
Hi, @gebes , your package is explicitly named `native_ios_dialog`, meaning it is intended for IOS, that and you didnt seem to maintain your package when I created this one.

Sorry if this annoyed you, I'm only trying to contribute to the community.

Best regards, and Kudos to you for laying the foundations of this package
